---
- name: Installation
  hosts: all
  become: yes
  vars: 
    user: "benjamin"

  roles:
    # - firewall
    # - ssh
    # - user
    - docker
    - git

  tasks: 
    - name: Update apt cache
      apt:
        update_cache: yes