---
- name: Installation
  hosts: all
  become: yes

  vars: 
    user: "benjamin"

  tasks: 
    - name: Update apt cache
      apt:
        update_cache: yes

  roles:
    - firewall
    - ssh
    - user
    - docker
    - git