---
- name: Update projects
  hosts: update_vps
  become: yes

  vars_files:
    - ../groups_vars/playbooks.yml

  tasks:
    - name: Clone all projects
    - name: Update all projects
    - name: Restart all projects with docker compose
    